version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3
    ports:
      - "15672:15672"
      - "5672:5672"


  producer:
    build:
      context: ./creating_microservices/producer
    depends_on:
      - rabbitmq
    environment:
      - RABBITMQ_HOST=rabbitmq


  consumer:
    build:
      context: ./creating_microservices/consumer
    depends_on:
      - rabbitmq
    environment:
      - RABBITMQ_HOST=rabbitmq
